# Generated by Django 3.2.15 on 2023-03-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_auto_20230316_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
