# Generated by Django 3.2.15 on 2023-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
