# Generated by Django 3.2.15 on 2023-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_alter_policies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
