# Generated by Django 3.2.15 on 2023-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0007_alter_notification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
