# Generated by Django 3.2.15 on 2023-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0008_alter_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.TextField(),
        ),
    ]
