# Generated by Django 3.2.15 on 2023-03-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0010_auto_20230331_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='description',
            field=models.TextField(),
        ),
    ]
