# Generated by Django 3.2.15 on 2023-03-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0003_auto_20230316_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='post',
            field=models.CharField(max_length=100),
        ),
    ]
